# Generated by Django 3.0.6 on 2020-05-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20200527_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoticeImage', models.ImageField(blank=True, upload_to='Notice')),
                ('NoticeTitle', models.CharField(max_length=200)),
                ('NoticeDescription', models.CharField(max_length=200)),
                ('NoticeDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='headerimage',
            name='img',
            field=models.ImageField(blank=True, upload_to='headers'),
        ),
        migrations.AlterField(
            model_name='homecontents',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='UserImage',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
